default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: Tiw@rikush13
  host: localhost
  pool: 5

development:
  <<: *default
  database: event_booking_development

test:
  <<: *default
  database: event_booking_test

production:
  <<: *default
  database: event_booking_production
